"""`Data/events.csv` — what happened, where, and who was there, and
`Data/places.csv` — the names the map prints over it.

    start,end,title,place,kind,lat,lon,people,note

`end` is blank for a single day; a trip carries both and the page prints the
range. `people` is semicolon-separated and holds names as written, deliberately
not keyed to `Data/people.csv`: a leaving do has forty attendees and nobody is
going to add forty rows to People before recording the party.

`kind` is a closed vocabulary, because it picks the glyph the map draws and a
one-off value would render as nothing at all. `lat`/`lon` are decimal degrees
and both optional — an event with no coordinate keeps its place in the timeline
and simply has no pin. That is the honest default: `place` is free text like
"My place" or "the usual izakaya", and most rows will never be worth a
coordinate.

Newest first, because the question asked of a list of events is almost always
"what happened lately", not "what happened first".
"""
import csv

from core.vault import VAULT

# What the map has a glyph for. `other` is the deliberate escape hatch, so a
# thing that fits none of these still gets a pin rather than being left off.
KINDS = ["trip", "study", "meal", "party", "work", "other"]


def num(v):
    try:
        return float(str(v).strip())
    except (TypeError, ValueError):
        return None


def read_events():
    """(events newest first, kinds nothing can draw)."""
    f = VAULT / "Data" / "events.csv"
    if not f.exists():
        return [], []
    rows, unknown = [], set()
    for r in csv.DictReader(f.open()):
        start = (r.get("start") or "").strip()
        title = (r.get("title") or "").strip()
        if not start or not title:
            continue
        kind = (r.get("kind") or "").strip().lower()
        if kind and kind not in KINDS:
            unknown.add(kind)
        lat, lon = num(r.get("lat")), num(r.get("lon"))
        # A pin needs both halves. One without the other is a half-entered row,
        # and placing it on the equator would be worse than not placing it.
        if lat is None or lon is None:
            lat = lon = None
        rows.append({"start": start, "end": (r.get("end") or "").strip(),
                     "title": title, "place": (r.get("place") or "").strip(),
                     "kind": kind if kind in KINDS else "other",
                     "lat": lat, "lon": lon,
                     "people": [p.strip() for p in (r.get("people") or "").split(";")
                                if p.strip()],
                     "note": (r.get("note") or "").strip()})
    return sorted(rows, key=lambda e: e["start"], reverse=True), sorted(unknown)


def read_places():
    """The map's labels — a name, where it is, how close you have to be, and
    what it is.

        name,lat,lon,zoom,kind

    `kind` picks the mark drawn at the point: `station` gets a chip with a
    train on it, blank gets a bare name. It is a column rather than something
    inferred from `zoom`, because the tier says how close you have to be and
    that is a different question from what the thing is — a bar you keep going
    back to belongs at the stations' tier without also claiming to be one.

    Two files, same columns, read as one list. `places.csv` is written by hand
    and holds the handful of names you chose: a city, a ward, the venue you keep
    going back to. `stations.csv` is 594 rows generated by `tonames.py` from
    Overpass and will be overwritten whole the next time it runs, so a name you
    care about does not belong in it. That is the only reason they are separate
    — a hand-kept file and a regenerated one should not be the same file — and
    nothing downstream can tell which row came from where.

    These are labels, not events: nothing happened at "Setagaya", it is simply
    what that part of the map is called. Two jobs, and the second is the one
    that earns the file.

    The first is captions. A pin in Ginza and a pin in Kanda are 1.4 km apart,
    which the world map draws as the same dot; what tells them apart is not the
    coastline between them but the ward name printed under each. Names do the
    work geometry cannot at this scale.

    The second is that `zoom` is how far the map is willing to go. The old cap
    was a constant justified by the basemap's accuracy — Natural Earth 1:10m is
    wrong by about k/4 pixels at scale k, so 16 was where a bay still read as
    that bay. But a name has no coastline to be wrong about. So the map now
    zooms as deep as the local labels can support and no deeper, which means
    adding a row here is how you make a place worth looking at closely. A
    coordinate with nothing named near it still stops at the old cap, because
    there would be nothing on screen to tell you where you had arrived.

    `zoom` is a frame scale, not a slippy-map zoom level: 8000 puts about two
    kilometres across the frame, 390 fills it with Tokyo's 23 wards, 30 shows a
    prefecture, 3 shows the country. A row is dropped rather than guessed at if
    any of the three numbers is missing — half a label is a name floating in
    the wrong ocean.
    """
    out = []
    for stem in ("places", "stations"):
        f = VAULT / "Data" / ("%s.csv" % stem)
        if not f.exists():
            continue
        for r in csv.DictReader(f.open()):
            name = (r.get("name") or "").strip()
            lat, lon = num(r.get("lat")), num(r.get("lon"))
            zoom = num(r.get("zoom"))
            if not name or lat is None or lon is None or not zoom or zoom <= 0:
                continue
            out.append({"name": name, "lat": lat, "lon": lon, "zoom": zoom,
                        "kind": (r.get("kind") or "").strip()})
    return out
